name: mobile_app
description: A new Flutter project.

publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.4
  mockito: ^4.1.1
  url_launcher: ^6.0.2
  http: ^0.12.1
  transparent_image: ^1.0.0
  flutter_svg: ^0.19.3
  flutter_icons: ^1.1.0
  get: ^3.26.0
  intl: ^0.17.0
  datetime_picker_formfield: ^2.0.0
  timeago: ^3.0.2
  google_sign_in: ^4.5.1
  oauth2_client: ^1.4.2
  html: ^0.14.0+3
  animations: ^2.0.0
  flutter_facebook_login: ^3.0.0
  flutter_html: ^1.0.2
  flutter_summernote: ^0.2.3
  theme_provider: ^0.5.0
  flutter_typeahead: ^3.0.0-nullsafety.0
  flutter_keyboard_visibility: ^5.0.0
  photo_view: ^0.11.1
  share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  pedantic: ^1.9.0

dependency_overrides:
  mime: ^0.9.7
  plugin_platform_interface: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/landing/
    - assets/images/homepage/
    - assets/images/contribute/
    - assets/images/teachers/
    - assets/images/login/
    - assets/images/signup/
    - assets/images/group/
    - assets/images/profile/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
