name: mobile_app
description: A new Flutter project.

publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.0
  cupertino_icons: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  flutter_facebook_auth: ^3.5.0
  flutter_html: ^2.0.0
  flutter_icons: ^1.1.0
  flutter_keyboard_visibility: ^5.0.2
  flutter_summernote: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_typeahead: ^3.1.3
  get: ^4.1.4
  get_it: ^7.1.3
  google_sign_in: ^5.0.4
  html: ^0.15.0
  http: ^0.13.3
  intl: ^0.17.0
  mockito: ^5.0.10
  oauth2_client: ^2.2.2
  photo_view: ^0.11.1
  provider: ^5.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  theme_provider: ^0.5.0
  timeago: ^3.1.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.9
  flutter_markdown:
    git:
      url: git://github.com/CircuitVerse/packages.git
      path: packages/flutter_markdown
  html_unescape: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_math_fork: ^0.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  hive_generator: ^1.1.0
  build_runner: ^2.0.5

dependency_overrides:
  mime: ^0.9.7
  plugin_platform_interface: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/landing/
    - assets/images/homepage/
    - assets/images/contribute/
    - assets/images/teachers/
    - assets/images/login/
    - assets/images/signup/
    - assets/images/group/
    - assets/images/profile/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
