name: mobile_app
description: Circuitverse mobile app

publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  animations: ^2.0.2
  cupertino_icons: ^1.0.4
  datetime_picker_formfield: ^2.0.0
  flutter:
    sdk: flutter
  
  flutter_inappwebview: ^6.1.5
  # flutter_facebook_auth: ^5.0.6
  flutter_html: ^3.0.0-alpha.6
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.6+2
  flutter_math_fork: ^0.7.3
  flutter_svg: ^2.0.17
  flutter_typeahead: ^5.2.0
  fluttericon: ^2.0.0
  get: ^4.6.1
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html: ^0.15.6
  html_unescape: ^2.0.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mockito: ^5.4.5
  path_provider: ^2.0.11
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  oauth2_client: ^4.1.0
  provider: ^6.0.2
  scroll_to_index: ^3.0.1
  share_plus: ^10.1.4
  shared_preferences: ^2.0.12
  showcaseview: ^4.0.1
  simple_chips_input: ^1.2.1
  theme_provider: ^0.6.0
  timeago: ^3.1.0
  transparent_image: ^2.0.0
  url_launcher: ^6.1.11
  flutter_facebook_auth: ^6.0.4

  http: any
  markdown: any
  webview_flutter: any
  flutter_quill: ^11.1.2
dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

  webview_flutter_platform_interface: 2.11.0
  webview_flutter_android: 4.3.5
  collection: any
dependency_overrides:
  mime: ^1.0.1
  plugin_platform_interface: ^2.1.2
  markdown:
    git: https://github.com/dart-lang/markdown.git

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/landing/
    - assets/images/homepage/
    - assets/images/contribute/
    - assets/images/teachers/
    - assets/images/login/
    - assets/images/signup/
    - assets/images/group/
    - assets/images/profile/
    - assets/images/projects/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
